### ISSUE TITLE
[Security] Command Injection in pdf-officegen

### ISSUE THREAD

**Issue by kapytein** [SpiderStrategies/pdf-officegen#16]
Hi.

A vulnerability was found in your module. I'd like to invite you to the HackerOne submission if possible (I require your account name on HackerOne or any e-mail for that), in order to responsibly disclose the issue. If you prefer that the details of the issue is shared in a public issue, I will go ahead and disclose the details here. 

kapytein

**Comment by kapytein** [comment]
@scottoreilly.

**Comment by codecounselor** [comment]
We are fine with a public disclose here in this issue, thanks

**Comment by kapytein** [comment]
Sure @codecounselor.

At https://github.com/SpiderStrategies/pdf-officegen/blob/master/lib/engine.js#L202, we could clearly see that the arguments are not passed as an array into child_process.exec(). This will allow command injection. It's probably better to make use of `spawn` or `execFile` in this case. 

Given the fact that file name is often controlled by user input, an user would be able to inject arbitrary shell commands.

Steps To Reproduce:
```javascript
const pdf = require('pdf-officegen');

const p = new pdf.Powerpoint({
    engine: 'mupdf',
})

const options = {};

p.convertFromPdf(["test.pdf | touch hello5.txt |.pdf", "test2.pdf"], options, (err, result) => {

    if(err) {
        console.log("oopsie");
        console.log(result);
    }
});
```

You'll notice that hello5.txt is created in the cwd.

The vulnerability occurs in more methods (for the different engines mupdf/ghostscript/inkscape) in engine.js.

**Comment by mattsgarlata** [comment]
Thank you @kapytein!  @codecounselor please fix this when you have a chance

**Comment by vdeturckheim** [comment]
Hey, do you have any ETA for a patched version? I would like request a CVE for this.

**Comment by codecounselor** [comment]
I just opened https://github.com/SpiderStrategies/pdf-officegen/pull/17 if you want to review and test your application against that version.

I need to complete a few integration tests yet and then I'll merge and publish this in a day or so.

**Comment by codecounselor** [comment]
released https://www.npmjs.com/package/pdf-officegen/v/2.0.2
